---
- hosts: "{{ variable_host | default('webservers') }}" 
  become: yes
  vars_files:
    - vars/default.yml
  tasks:
    - name: Stop Apache
      service:
        name: apache2
        state: stopped
        notify: Uninstall Apache
  handlers:
    - name: Uninstall Apache
      apt:
        name: apache2
        state: absent
        register: uninstalled
        listen: start uninstall
    - name: Clean Up firewall rules
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp
        delete: yes
        when: uninstalled
        listen: start uninstall
...
